"""empty message

Revision ID: c9abe193eb19
Revises: d159cfaeeb8f
Create Date: 2020-04-13 12:02:17.177444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9abe193eb19'
down_revision = 'd159cfaeeb8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artists', ['name'])
    op.create_unique_constraint('name_city_state', 'venues', ['city', 'state', 'name'])
    op.create_unique_constraint('total_address', 'venues', ['city', 'state', 'address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('total_address', 'venues', type_='unique')
    op.drop_constraint('name_city_state', 'venues', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    # ### end Alembic commands ###
